name: jetlag_sync
description: TCM Vision Assistant - 中医望诊辅助系统
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.11.0+2
  camera_windows: ^0.2.6+4
  google_fonts: ^6.2.1
  perfect_freehand: ^2.0.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
